version: "3.9"

x-default-opts: &default-opts
  logging:
    options:
      max-size: "100m"

services:
  postgres:
    image: pgvector/pgvector:pg16
    # env_file: .env
    volumes:
      - ./pgvec_data/:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=langchain
      - POSTGRES_USER=langchain
      - POSTGRES_PASSWORD=langchain
